### ISSUE TITLE
the second batch of training data

### ISSUE THREAD

**Issue by tjboise** [UM-Titan/DSPS23#1]
for Track 1, where I can find the sencond batch image?

**Comment by UM-Titan** [comment]
There will be no second batch of images this time. So just use the data shared via  the notebook to train and evaluate your model.

**Comment by tjboise** [comment]
Ok, thank you for clarification! 
I would suggest change the discription for track 1's second data release  in https://dsps-1e998.web.app/data as it is a little confusing.

well, thanks anyway.
